spring:
  mongodb:
    uri: mongodb+srv://bt23cse242_db_user:3mIPCNa1PexZSyk4@cluster0.heakkmr.mongodb.net/?appName=Cluster0
    database: journaldb
    auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal

weather:
  api:
    key: 4323a1ea7e845447da5dc3ce2fd9b218