spring:
  mongodb:
    uri: mongodb+srv://bt23cse242_db_user:3mIPCNa1PexZSyk4@cluster0.heakkmr.mongodb.net/?appName=Cluster0
    database: journaldb
    auto-index-creation: true

server:
  port: 9090
  servlet:
    context-path: /journal